- link:
    ~/.ssh/config: tools/ssh-config-base
    ~/.ssh/config.d/github: tools/ssh-config-github
    ~/.ssh/config.d/gitlab: tools/ssh-config-gitlab
    ~/.ssh/config.d/sloegin: tools/ssh-config-sloegin
    ~/.ssh/config.d/dewberry: tools/ssh-config-dewberry
