- link:
    # Vim
    ~/.vimrc: tools/vimrc
    ~/.vim/init.vim: tools/vimrc
    ~/.vim/coc-settings.json: tools/coc-settings.json

    # NVim
    ~/.config/nvim/init.vim: tools/vimrc
    ~/.config/nvim/coc-settings.json: tools/coc-settings.json
