" line numbering
set number

" syntax highlighting
syntax on

" new windows should intuitively be split to the bottom-right
set splitright
set splitbelow

" copy to the x-windows clipboard by default
set clipboard=unnamedplus

" search as soon as we start typing
set incsearch

" copy indentation from previous line
set autoindent
