# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
  export ZSH=/home/tom/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes

ZSH_THEME="powerlevel9k/powerlevel9k"

# Custom dir style
POWERLEVEL9K_SHORTEN_DIR_LENGTH="2"
POWERLEVEL9K_SHORTEN_STRATEGY="default"
POWERLEVEL9K_SHORTEN_DELIMITER="*"

# Mostly hide context
DEFAULT_USER="tom"

# Warn when AWS DB set
POWERLEVEL9K_CUSTOM_DB_WARNING='[[ $DATABASE_URL = *"aws"* ]] && echo "$fg_bold[white]AWS DB$fg_no_bold[white]"'
POWERLEVEL9K_CUSTOM_DB_WARNING_BACKGROUND="red"

# Warn when AWS DB set
POWERLEVEL9K_CUSTOM_RVM='[[ $RUBY_VERSION != *"2.2.8"* ]] && echo $RUBY_VERSION'
POWERLEVEL9K_CUSTOM_RVM_BACKGROUND="197"
POWERLEVEL9K_CUSTOM_RVM_FOREGROUND="black"

POWERLEVEL9K_NVM_FOREGROUND="black"

POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="208"
POWERLEVEL9K_DIR_HOME_BACKGROUND="255"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="255"

# Prompt element configuration
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir virtualenv nvm custom_rvm docker_machine vcs custom_db_warning)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs)


# Set list of themes to load
# Setting this variable when ZSH_THEME=random
# cause zsh load theme from this variable instead of
# looking in ~/.oh-my-zsh/themes/
# An empty array have no effect
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
  docker
  docker-compose
  dotenv
  history
  npm
  nvm
  pip
  python
  rust
  rvm
  tmux
  ubuntu
  vi-mode
  yarn
)

source $ZSH/oh-my-zsh.sh

# User configuration

# reinstate fuzzy up/down search when using vi mode
# start typing + [Up-Arrow] - fuzzy find history forward
if [[ "${terminfo[kcuu1]}" != "" ]]; then
  autoload -U up-line-or-beginning-search
  zle -N up-line-or-beginning-search
  bindkey "${terminfo[kcuu1]}" up-line-or-beginning-search
fi
# start typing + [Down-Arrow] - fuzzy find history backward
if [[ "${terminfo[kcud1]}" != "" ]]; then
  autoload -U down-line-or-beginning-search
  zle -N down-line-or-beginning-search
  bindkey "${terminfo[kcud1]}" down-line-or-beginning-search
fi


# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

export-envfile(){
  if [ "$#" -ne 1 ]; then
    printf "Usage: export-envfile <env-file>
Export an environment file into the current shell.
File must be in the format:
<KEY>=<VALUE>
" >&2
    return 3
  fi
  export $(cat $1 | xargs)
}

alias random-boolean='if (( RANDOM % 2 )); then false; fi'
alias yaml-as-json='python -c "import json, sys, yaml; fh = open(sys.argv[1]); print(json.dumps(yaml.load(fh), indent=2)); fh.close"'

git-check(){
  if [ "$#" -ne 2 ]; then
    printf "Usage: git-check <diff-base> <path-regex>
Check file paths modified since <commit> match <regex>.
Non-matching paths will be printed on stdout.
" >&2
    return 3
  fi
  # Filepaths
  git diff --name-only "$1" | \
  # Filter by regex, return success if nothing found
  grep -vE "$2" || return 0
  # If grep successfully got some files, return error code
  return 4
}

# Add yarn
YARN_HOME="$HOME/.yarn"
[[ -d "$YARN_HOME" ]] && export PATH=$PATH:$YARN_HOME/bin
alias yarn-count='yarn list | sed -r "s/^\W*([\.a-zA-Z0-9-]+)@.*$/\1/" | wc -l'
alias yarn-count-pkg='yarn list | sed -r "s/^\W*([\.a-zA-Z0-9-]+)@.*$/\1/" | sort | uniq | wc -l'

# Add RVM.
RVM_HOME="/usr/share/rvm"
[[ -d "$RVM_HOME/bin" ]] && export PATH=$PATH:$RVM_HOME/bin
[[ -s "$RVM_HOME/scripts/rvm" ]] && . "$RVM_HOME/scripts/rvm"



